version: "3"

volumes:
  db-data:

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn main.wsgi -b :8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - SECRET_KEY
    restart: unless-stopped
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - DEFAULT_DATABASE_NAME
      - DEFAULT_DATABASE_USER
      - DEFAULT_DATABASE_PASSWORD
      - DEFAULT_DATABASE_HOST
      - DEFAULT_DATABASE_PORT
    restart: unless-stopped
