version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dicpick
      POSTGRES_USER: dicpick
      POSTGRES_PASSWORD: dicpick
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
