# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 15:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicpick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='do_not_assign_to',
            field=models.ManyToManyField(blank=True, related_name='unassignable_tasks', to='dicpick.Participant'),
        ),
    ]
