# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicpick', '0002_auto_20160421_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='participants', to='dicpick.Label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='dicpick.Label'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_types', to='dicpick.Label'),
        ),
    ]
